name: Testflight build

on:
  workflow_dispatch:
    inputs:
      buildNumber:
        description: 'Build number'
        required: false

jobs:
  testflight-build:
    name: Creating new iOS build and uploding it to the Testflight
    runs-on: macos-latest
    environment: ios
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install SSH key to get acces to the Certificates and Provisioning profiles
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Generate Changelog
        run: echo "CHANGELOG=$(git log --pretty=format:'%s' origin/master..origin/development)" >> $GITHUB_ENV

      - run: echo "$(git log --pretty=format:'%s' origin/master..origin/development)"
      - run: echo "${{ env.CHANGELOG }}"
      - run: echo "${{ env.TEST_ENV }}"
        env:
          TEST_ENV: $(git log --pretty=format:'%s' origin/master..origin/development)
      - run: git log --pretty=format:'%s' origin/master..origin/development

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Install Pods
        run: yarn ios:pods

      - name: Build & Distribute to Testflight
        run: |
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          cd ios && ./decrypt_authkey.sh
          yarn ios:test-flight
        env:
          BUILD_NUMBER: ${{ github.event.inputs.buildNumber }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APPSTORE_AUTHKEY: ${{ secrets.APPSTORE_AUTHKEY }}
          CHANGELOG: ${{ env.CHANGELOG }}

      - name: Commit changes
        run: |
          git commit -am "Build number increased"
          git push
