name: Testflight build

on:
  workflow_dispatch:
    inputs:
      buildNumber:
        description: 'Build number'
        required: true

jobs:
  testflight-build:
    name: Creating new iOS build and uploding it to the Testflight
    runs-on: macos-latest
    environment: ios
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Test clone
        run: git clone https://github.com/madfish-solutions/templewallet-mobile-certificates.git
        with:
          repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Install SSH key to get acces to the Certificates and Provisioning profiles
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install dependencies
        run: yarn install

      - name: Install Pods
        run: yarn ios:pods

      - name: Build & Distribute to Testflight
        run: |
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          cd ios && ./decrypt_authkey.sh
          yarn ios:test-flight
        env:
          BUILD_NUMBER: ${{ github.event.inputs.buildNumber }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APPSTORE_AUTHKEY: ${{ secrets.APPSTORE_AUTHKEY }}
